### PR TITLE
Fix swagger request schemes

### PR DESCRIPTION
**Pull request by jwhite3**
*What does this PR do?*
This PR fixes allowed schemes for the swagger docs ui.

*Changes*
- Add manual schemes list

### CODE REVIEW

**Review by amyd11 — APPROVED** [review]
Code changes make sense. This seems like something that's hard to test locally- I think it's safe to merge then test (and we can always continue to fix if necessary!)

**Comment by jwhite3** [comment]
> Code changes make sense. This seems like something that's hard to test locally- I think it's safe to merge then test (and we can always continue to fix if necessary!)

Yeah, I had no idea how to actually do that in a test :/

**Comment by jauschalley** [comment]
> > Code changes make sense. This seems like something that's hard to test locally- I think it's safe to merge then test (and we can always continue to fix if necessary!)
> 
> Yeah, I had no idea how to actually do that in a test :/

I think there is a way to lock down docker to HTTPS between containers but I'm really not sure how to do this within the Django app itself.

**Review by jauschalley — APPROVED** [review]
Thanks!

**Pull request merged**
